[project]
name = "observatorio-etl"
version = "0.1.0"
description = "ETL em Python para dados públicos brasileiros"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.0",
    "pandas>=2.2.0",
    "pyarrow>=16.0.0"
]

[project.scripts]
observatorio-etl = "observatorio_etl.cli:main"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"
